import { test, expect } from '@playwright/test'

test.describe('Overview Page', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
  })

  test('loads and displays project name', async ({ page }) => {
    await expect(page.locator('h1')).toBeVisible()
    await expect(page.locator('h1')).toHaveText('jaffle_shop')
  })

  test('displays stat cards with correct counts', async ({ page }) => {
    const stats = page.locator('.grid > div')
    await expect(stats).toHaveCount(4)

    await expect(stats.nth(0)).toContainText('Models')
    await expect(stats.nth(1)).toContainText('Sources')
    await expect(stats.nth(2)).toContainText('Seeds')
    await expect(stats.nth(3)).toContainText('Tests')
  })

  test('displays health summary with grade', async ({ page }) => {
    await expect(page.getByText('Project Health')).toBeVisible()
    // Grade letter visible in the health card
    await expect(page.getByText('64/100')).toBeVisible()
  })

  test('health card navigates to health page on click', async ({ page }) => {
    await page.getByText('Project Health').click()
    await expect(page).toHaveURL(/#\/health/)
  })

  test('displays recent models table', async ({ page }) => {
    await expect(page.getByText('Recent Models')).toBeVisible()
    const table = page.locator('table')
    await expect(table).toBeVisible()
    await expect(table.locator('th')).toHaveCount(4)
  })

  test('clicking a model row navigates to model page', async ({ page }) => {
    const firstRow = page.locator('table tbody tr').first()
    await firstRow.click()
    await expect(page).toHaveURL(/#\/model\//)
  })

  test('displays docglow version info', async ({ page }) => {
    await expect(page.getByText(/Generated by docglow/)).toBeVisible()
  })
})
